//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LoftyCAD.rc
//
#define IDC_MYICON                      2
#define IDB_RECT                        5
#define IDB_EDGE                        6
#define IDB_CIRCLE                      7
#define IDB_CONST_RECT                  8
#define IDB_CONST_EDGE                  9
#define IDB_CONST_CIRCLE                10
#define IDB_POINT                       11
#define IDB_SCALE                       11
#define IDB_XY                          12
#define IDB_YZ                          13
#define IDB_EXTRUDE                     14
#define IDB_XZ                          15
#define IDB_MINUS_XY                    16
#define IDB_ARC_EDGE                    17
#define IDB_MINUS_YZ                    18
#define IDB_MINUS_XZ                    19
#define IDB_BEZIER_EDGE                 20
#define IDB_ROUND_RECT                  21
#define IDB_RENDERED                    21
#define IDB_CHAMFER_RECT                22
#define IDB_ROTATE                      22
#define IDB_TEXT                        23
#define IDB_EXTRUDE_LOCAL               24
#define IDD_LOFTYCAD_DIALOG             102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDS_RECT                        104
#define IDM_EXIT                        105
#define IDS_CONST_RECT                  105
#define IDS_EDGE                        106
#define IDI_LOFTYCAD                    107
#define IDS_CONST_EDGE                  107
#define IDS_CIRCLE                      108
#define IDC_LOFTYCAD                    109
#define IDS_CONST_CIRCLE                110
#define IDS_POINT                       111
#define IDS_EXTRUDE                     112
#define IDS_XY                          113
#define IDS_YZ                          114
#define IDS_XZ                          115
#define IDS_MINUS_XY                    116
#define IDS_MINUS_YZ                    117
#define IDS_MINUS_XZ                    118
#define IDS_ARC_EDGE                    119
#define IDS_BEZIER_EDGE                 120
#define IDS_RENDERED                    121
#define IDS_SCALE                       122
#define IDS_ROTATE                      123
#define IDS_TEXT                        124
#define IDS_EXTRUDE_LOCAL               125
#define IDR_MAINFRAME                   128
#define IDD_TOOLBAR                     129
#define IDI_RECT                        131
#define IDI_EDGE                        132
#define IDI_CIRCLE                      133
#define IDD_DEBUG                       134
#define IDI_CONST_RECT                  135
#define IDI_CONST_EDGE                  136
#define IDI_CONST_CIRCLE                137
#define IDI_EXTRUDE                     140
#define IDD_DIMENSIONS                  141
#define IDD_PREFS                       142
#define IDR_CONTEXT                     143
#define IDD_HELP                        143
#define IDI_ARC_EDGE                    144
#define IDD_TREEVIEW                    144
#define IDI_BEZIER_EDGE                 145
#define IDI_ICON2                       147
#define IDI_RIGHT                       149
#define IDB_PNG1                        150
#define IDI_BACK                        151
#define IDI_BOTTOM                      152
#define IDI_FRONT                       153
#define IDI_LEFT                        154
#define IDI_RENDERED                    155
#define IDI_TOP                         156
#define IDD_TRANSFORM                   157
#define IDI_SCALE                       158
#define IDI_ROTATE                      159
#define IDC_SQUIGGLE                    160
#define IDI_TEXT                        160
#define IDI_EXTRUDE1                    161
#define IDI_EXTRUDE_LOCAL               161
#define IDC_EDGE1                       162
#define IDD_MATERIALS                   162
#define IDC_EDGE2                       163
#define IDR_OPENORIMPORT                163
#define IDC_EDGE3                       164
#define IDR_CONTEXT_GROUP               164
#define IDC_FACE                        165
#define IDR_CONTEXT_VOL                 165
#define IDC_FACE1                       166
#define IDR_CONTEXT_FACE                166
#define IDC_FACE2                       167
#define IDR_CONTEXT_EDGE                167
#define IDC_FACE3                       168
#define IDR_CONTEXT_SELECTION           168
#define IDC_RESIZE                      169
#define IDC_RESIZE1                     170
#define IDC_RESIZE2                     171
#define IDC_FACE4                       172
#define IDC_DEBUG                       1002
#define IDB_CLEARDEBUG                  1003
#define IDC_DIMENSIONS                  1004
#define IDC_PREFS_TITLE                 1005
#define IDC_PREFS_HALFSIZE              1006
#define IDC_PREFS_GRID                  1007
#define IDC_PREFS_TOL                   1008
#define IDC_PREFS_ANGLE                 1009
#define IDC_CONTEXT_HELP                1009
#define IDC_PREFS_ROUNDRAD              1010
#define IDC_TREEVIEW                    1013
#define IDC_STATIC_BUILD                1014
#define IDC_SCALE_X                     1015
#define IDC_SCALE_Z                     1016
#define IDC_SCALE_Y                     1017
#define IDC_ROTATE_X                    1018
#define IDC_ROTATE_Y                    1019
#define IDC_ROTATE_Z                    1020
#define IDC_CHECK_SCALE                 1021
#define IDC_CHECK_ROTATE                1022
#define IDC_CENTRE_X                    1023
#define IDC_CENTRE_Y                    1024
#define IDC_CENTRE_Z                    1025
#define IDC_APPLY                       1027
#define IDC_REMOVE                      1028
#define IDC_TITLE                       1029
#define IDC_FONT_STRING                 1030
#define IDC_COMBO_MATERIAL              1031
#define IDC_STATIC_MAT_INDEX            1032
#define IDC_MATERIAL_NAME               1033
#define IDC_MATERIAL_RED                1034
#define IDC_MATERIAL_GREEN              1035
#define IDC_MATERIAL_BLUE               1036
#define IDC_MATERIAL_SHINY              1037
#define ID_FILE_NEW                     32774
#define ID_FILE_OPEN                    32775
#define ID_FILE_SAVE                    32776
#define ID_FILE_SAVEAS                  32777
#define ID_EDIT_UNDO                    32778
#define ID_EDIT_CUT                     32779
#define ID_EDIT_COPY                    32780
#define ID_EDIT_PASTE                   32781
#define ID_FILE_EXPORT                  32782
#define ID_VIEW_TOOLS                   32783
#define ID_VIEW_DEBUGLOG                32784
#define ID_VIEW_RENDEREDVIEW            32785
#define ID_VIEW_TOP                     32790
#define ID_VIEW_                        32791
#define ID_VIEW_FRONT                   32792
#define ID_VIEW_BOTTOM                  32793
#define ID_VIEW_RIGHT                   32794
#define ID_VIEW_BACK                    32795
#define ID_VIEW_LEFT                    32796
#define ID_VIEW_PERSPECTIVE             32797
#define ID_VIEW_ORTHO                   32798
#define ID_Menu                         32799
#define ID_FILE_PREFS                   32800
#define ID_EDIT_SNAPTOGRID              32801
#define ID_EDIT_SNAPTOGRID32802         32802
#define ID_EDIT_SNAP                    32803
#define ID_OBJECTTYPE_SELECTPARENTVOLUME 32804
#define ID_OBJECTTYPE_LOCKING           32805
#define ID_LOCKING_VOLUME               32806
#define ID_LOCKING_FACES                32807
#define ID_LOCKING_EDGES                32808
#define ID_LOCKING_POINTS               32809
#define ID_LOCKING_UNLOCKED             32810
#define ID_OBJECTTYPE_ENTERDIMENSIONS   32811
#define ID_OBJECTTYPE_OBJECTTYPE        32812
#define ID_OBJ_OBJECTTYPE               32813
#define ID_OBJ_SELECTPARENTVOLUME       32814
#define ID_OBJ_ENTERDIMENSIONS          32815
#define ID_EDIT_DELETE                  32816
#define ID_Menu32817                    32817
#define ID_EDIT_SELECTALL               32818
#define ID_PREFERENCES_SNAPTOGRID       32819
#define ID_PREFERENCES_SNAPTOANGLE      32820
#define ID_PREFERENCES_SETTINGS         32821
#define ID_FILE_RECENTFILES             32822
#define ID_RECENTFILES_RECENTFILES      32823
#define ID_VIEW_HELPANDSUGGESTIONS      32824
#define ID_VIEW_HELP                    32825
#define ID_EDIT_SELECTNONE              32828
#define ID_EDIT_REDO                    32829
#define ID_VIEW_ORIENTATION             32839
#define ID_VIEW_CONSTRUCTIONEDGES       32840
#define ID_OBJ_ALWAYSSHOWDIMENSIONS     32841
#define ID_OBJ_ALWAYSSHOWDIMS           32842
#define ID_OBJ_GROUPCONNECTEDEDGES      32843
#define ID_OBJ_GROUPSELECTED            32844
#define ID_OBJ_UNGROUP                  32845
#define ID_OBJ_MAKEFACEFROMEDGEGROUP    32846
#define ID_OBJ_GROUPEDGES               32847
#define ID_OBJ_MAKEFACE                 32848
#define ID_VIEW_OBJECTTREE              32849
#define ID_VIEW_TREE                    32850
#define ID_FILE_IMPORTTOGROUP           32851
#define ID_VIEW_CLIPPEDFACEVIEW         32852
#define ID_VIEW_CLIPPEDFACE             32853
#define ID_VIEW_DEBUG                   32854
#define ID_DEBUG_HIGHLIGHTADJACENTVOLUMES 32855
#define ID_DEBUG_HIGHLIGHTBOUNDINGBOXES 32856
#define ID_DEBUG_ADJACENT               32857
#define ID_DEBUG_BBOXES                 32858
#define ID_DEBUG_HIGHLIGHTSURFACEINTERSECTIONS 32859
#define ID_DEBUG_INTER                  32860
#define ID_OBJ_GROUPING                 32861
#define ID_OBJ_CHAMFERCORNER            32862
#define ID_OBJ_ROUNDCORNER              32863
#define ID_HELP_GETTINGSTARTED          32864
#define ID_HELP_DRAWINGFACES            32865
#define ID_HELP_EXTRUDING               32866
#define ID_HELP_LOCKINGANDGROUPING      32867
#define ID_HELP_IMPORTANDEXPORT         32868
#define ID_VIEW_BLENDMODE               32869
#define ID_BLENDMODE_ALPHABLENDING      32870
#define ID_BLENDMODE_MULTIPLYBLENDING   32871
#define ID_VIEW_BLEND_ALPHA             32872
#define ID_VIEW_BLEND_MULTIPLY          32873
#define ID_VIEW_BLEND_OPAQUE            32874
#define ID_DEBUG_NORMALS                32875
#define ID_OBJ_TRANSFORM                32876
#define ID_FILE_SAVEGROUPAS             32877
#define ID_GROUPING_SAVEGROUPAS         32878
#define ID_GROUPING_SAVEGROUP           32879
#define ID_OBJ_SAVEGROUP                32880
#define ID_HELP_DRAWINGTEXT             32881
#define ID_OBJ_EDITTEXT                 32882
#define ID_OBJ_RENDERINGOPERATION       32883
#define ID_RENDERINGOPERATION_UNION     32884
#define ID_OPERATION_UNION              32885
#define ID_RENDERINGOPERATION_INTERSECTION 32886
#define ID_RENDERINGOPERATION_DIFFERENCE 32887
#define ID_RENDERINGOPERATION_          32888
#define ID_OPERATION_INTERSECTION       32889
#define ID_OPERATION_DIFFERENCE         32890
#define ID_OPERATION_NONE               32891
#define ID_HELP_CSGOPERATIONS           32892
#define ID_VIEW_MATERIALS               32893
#define ID_MATERIALS_1                  32894
#define ID_MATERIALS_0                  32895
#define ID_MATERIALS_NEW                32896
#define ID_OBJ_MATERIAL                 32897
#define ID_MATERIAL_NEW                 32898
#define ID_LOCKING_GROUP                32899
#define ID_OPENFILE_IMPORTTOGROUP       32900
#define ID_OPENFILE_OPENFILE            32901
#define ID_FILE_OPENFILE                32902
#define ID_OBJ_REFLECT                  32903
#define ID_OBJ_ROTATE90                 32904
#define ID_OBJ_REFLECTSELECTED          32905
#define ID_OBJ_ROTATESELECTED90         32906
#define ID_DEBUG_HIGHLIGHTVIEWLISTPOINTS 32907
#define ID_DEBUG_VIEWLIST               32908
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32909
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
